apiVersion: skaffold/v4beta7
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - context: auth
      image: robertmarriott/auth
      docker:
        dockerfile: Dockerfile
        noCache: false
        pullParent: false
        squash: false
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
